### PR TITLE
Fix empty dispatching delivery

### LINKED ISSUE #1352: Aggregate tries to update its state after `@React`ion even when no events are produced
Assuming we've got the following reactor method:

```java
    @React
    Optional<AggProjectStarted> on(AggProjectStarted e) {
        return Optional.empty();
    }
```

When such a method is invoked by the framework for an aggregate, the framework then tries to validate and store the aggregate even though nothing modified the state.
Usually, it's not an issue, but when one adds some validation rules to the aggregate state, e.g.:

```protobuf
message StringAggregate {

    option (entity).kind = AGGREGATE;

    string id = 1;

    string value = 2 [(required) = true];
}
```

The validation of the state fails for such an aggregate and thus the dispatching fails as well. 

Here's the related stacktrace:
```
java.lang.IllegalStateException: Transaction failed but no messages were propagated.
	at com.google.common.base.Preconditions.checkState(Preconditions.java:508)
	at io.spine.server.entity.EntityLifecycleMonitor.onTransactionFailed(EntityLifecycleMonitor.java:163)
	at io.spine.server.entity.Transaction.lambda$rollback$1(Transaction.java:543)
	at io.spine.server.entity.Transaction.doRollback(Transaction.java:566)
	at io.spine.server.entity.Transaction.rollback(Transaction.java:543)
	at io.spine.server.entity.Transaction.doCommit(Transaction.java:411)
	at io.spine.server.entity.Transaction.commit(Transaction.java:383)
	at io.spine.server.entity.Transaction.commitIfActive(Transaction.java:364)
	at io.spine.server.aggregate.AggregateEndpoint.applyProducedEvents(AggregateEndpoint.java:151)
	at io.spine.server.aggregate.AggregateEndpoint.handleAndApplyEvents(AggregateEndpoint.java:130)
	at io.spine.server.aggregate.AggregateEndpoint.dispatchTo(AggregateEndpoint.java:80)
	at io.spine.server.delivery.InboxPart.lambda$deliver$1(InboxPart.java:118)
	at io.spine.server.delivery.InboxPart.lambda$callEndpoint$3(InboxPart.java:140)
	at io.spine.server.tenant.TenantAwareRunner$2.run(TenantAwareRunner.java:104)
	at io.spine.server.tenant.TenantAwareOperation.execute(TenantAwareOperation.java:80)
	at io.spine.server.tenant.TenantAwareRunner.run(TenantAwareRunner.java:106)
	at io.spine.server.delivery.InboxPart.callEndpoint(InboxPart.java:140)
	at io.spine.server.delivery.InboxPart.deliver(InboxPart.java:118)
	at io.spine.server.delivery.TargetDelivery.doDeliver(TargetDelivery.java:92)
	at io.spine.server.delivery.TargetDelivery.access$200(TargetDelivery.java:51)
	at io.spine.server.delivery.TargetDelivery$Batch.deliverVia(TargetDelivery.java:189)
	at io.spine.server.delivery.TargetDelivery$Batch.access$300(TargetDelivery.java:119)
	at io.spine.server.delivery.TargetDelivery.lambda$deliverInBatch$0(TargetDelivery.java:103)
	at io.spine.server.tenant.TenantAwareRunner$2.run(TenantAwareRunner.java:104)
	at io.spine.server.tenant.TenantAwareOperation.execute(TenantAwareOperation.java:80)
	at io.spine.server.tenant.TenantAwareRunner.run(TenantAwareRunner.java:106)
	at io.spine.server.delivery.TargetDelivery.deliverInBatch(TargetDelivery.java:102)
	at io.spine.server.delivery.TargetDelivery.deliver(TargetDelivery.java:73)
	at io.spine.server.delivery.GroupByTargetAndDeliver.executeFor(GroupByTargetAndDeliver.java:74)
	at io.spine.server.delivery.LiveDeliveryStation.process(LiveDeliveryStation.java:106)
	at io.spine.server.delivery.Delivery.launch(Delivery.java:494)
	at io.spine.server.delivery.Delivery.runDelivery(Delivery.java:466)
	at io.spine.server.delivery.Delivery.deliverMessagesFrom(Delivery.java:425)
	at io.spine.server.delivery.LocalDispatchingObserver.lambda$runDelivery$1(LocalDispatchingObserver.java:81)
	at io.spine.server.tenant.TenantAwareRunner$2.run(TenantAwareRunner.java:104)
	at io.spine.server.tenant.TenantAwareOperation.execute(TenantAwareOperation.java:80)
	at io.spine.server.tenant.TenantAwareRunner.run(TenantAwareRunner.java:106)
	at io.spine.server.delivery.LocalDispatchingObserver.runDelivery(LocalDispatchingObserver.java:81)
	at io.spine.server.delivery.LocalDispatchingObserver.onMessage(LocalDispatchingObserver.java:74)
	at io.spine.server.delivery.Delivery.onNewMessage(Delivery.java:545)
	at io.spine.server.delivery.DeliveryDispatchListener.lambda$propagateMessage$0(DeliveryDispatchListener.java:107)
	at io.spine.server.tenant.TenantAwareRunner$2.run(TenantAwareRunner.java:104)
	at io.spine.server.tenant.TenantAwareOperation.execute(TenantAwareOperation.java:80)
	at io.spine.server.tenant.TenantAwareRunner.run(TenantAwareRunner.java:106)
	at io.spine.server.delivery.DeliveryDispatchListener.propagateMessage(DeliveryDispatchListener.java:107)
	at io.spine.server.delivery.DeliveryDispatchListener.onCompleted(DeliveryDispatchListener.java:75)
	at io.spine.server.bus.MulticastBus.onDispatched(MulticastBus.java:81)
	at io.spine.server.bus.Bus.doPost(Bus.java:348)
	at io.spine.server.bus.Bus.filterAndPost(Bus.java:160)
	at io.spine.server.bus.Bus.post(Bus.java:152)
	at io.spine.server.event.EventBus.post(EventBus.java:220)
	at io.spine.testing.server.blackbox.BlackBoxSetup.postExternal(BlackBoxSetup.java:157)
	at io.spine.testing.server.blackbox.BlackBoxSetup.postExternalEvent(BlackBoxSetup.java:152)
	at io.spine.testing.server.blackbox.BlackBoxContext.receivesExternalEvent(BlackBoxContext.java:337)
```

### PR DESCRIPTION
**Pull request by yuri-sergiichuk**
This PR fixes #1352.

The root cause of the issue was using `hasProducedEvents` method which actually is just checking that the `ProducedEvents` message is set, but does not check if there are any events inside.

### CODE REVIEW

**Comment by yuri-sergiichuk** [comment]
@armiol @alexander-yevsyukov PTAL.

File: server/src/test/java/io/spine/server/aggregate/given/thermometer/SafeThermometer.java [hunk 1]
```diff
@@ -0,0 +1,75 @@
...
+import io.spine.server.aggregate.given.thermometer.event.TemperatureChanged;
+import io.spine.server.aggregate.given.thermometer.event.TermTemperatureChanged;
+import io.spine.server.event.React;
+
+import java.util.Optional;
+
+/**
+ * Ignores temperature changes outside its own range.
+ */
+public final class SafeThermometer extends Aggregate<ThermometerId, Thermometer, Thermometer.Builder> {
```
Comment (alexander-yevsyukov) [inline server/src/test/java/io/spine/server/aggregate/given/thermometer/SafeThermometer.java:41]: Грядущими морозами навеяло? ;)

**Review by alexander-yevsyukov — APPROVED** [review]
Elegantly solved! LGTM
