### PR TITLE
Fail tests on runtime exceptions

### LINKED ISSUE #1314: Fail tests if runtime exceptions are thrown in BBC
Currently, it's possible to receive a false-positive test when one uses BBC tests and verifies the expected state of an entity with a sequence of events that first do a change and then undo the change if runtime exceptions are thrown in the middle of the events processing.

Such runtime exceptions are always wrapped into `HandlerFailedUnexpectedly` event and one may subscribe to it which is fine when we're running in Production. But while testing the app, in most cases we do want to fail a test case if smth went wrong.

The proposed solution is to allow configuring the BBC behavior with "strict" and "lenient" modes. By default, the BBC should be instantiated in "strict" mode when *any* runtime issue fails the test case. One should be able to switch to the "lenient" mode, e.g. if she wants to test that a particular `HandlerFailedUnexpectedly` event is thrown. In the "lenient" mode we only log runtime exceptions but do not fail the test cases automatically (the current behavior of the BBC).

### PR DESCRIPTION
**Pull request by yuri-sergiichuk**
This PR resolves #1314.

## Potential breaking change for tests

From now on the BlackBox tests are gonna be failed if some signal handler failed in the background. Such a change is desired while it eliminates potential untested erroneous flows.

## `FailedHandlerGuard`

The new `FailedHandlerGuard` is responsible for tracking `HandlerFailedUnexpectedly` events and fail the tests as soon as such an event occurs. The guard can be configured to tolerate such handler failures and simply log the failure over failing a test.

The BBC users can use `tolerateFailures` method to configure the guard accordingly and fall back to the previous behavior.

### CODE REVIEW

**Comment by yuri-sergiichuk** [comment]
@alexander-yevsyukov @dmdashenkov PTAL.

File: .gitignore [hunk 1]
```diff
@@ -1,48 +1,95 @@
...
-# See sample file for a Mac OS X workstation below.
-# -------
-# # Set Java home to point to JDK8. This is need to generate classes working with Java8 API.
-# # Otherwise the following warning appears during the build:
-# #     warning: [options] bootstrap class path not set in conjunction with -source 1.8
-# #
-# # suppress inspection "UnusedProperty"
-# org.gradle.java.home=/Library/Java/JavaVirtualMachines/jdk1.8.0_51.jdk/Contents/Home/
-# -------
-gradle.properties
```
Comment (alexander-yevsyukov) [inline .gitignore:48]: Why do we want `gradle.properties` to be version-controlled now?

File: server/src/main/java/io/spine/server/model/ExternalCommandReceiverMethodError.java [hunk 2]
```diff
@@ -49,11 +50,15 @@
...
+    /**
+     * Creates a new exception for the command handler that violates the {@code @Command} semantic.
+     */
+    @Internal
     public ExternalCommandReceiverMethodError(
             CommandHandlingClass<?, ?> classWithViolation,
             Collection<? extends CommandAcceptingMethod<?, ?>> invalidMethods) {
-        super("The class `%s` declares `external` command receiver methods for command types: %s."
-                      + " Only event accepting methods should be marked as `external`.",
+        super("The class `%s` declares `external` command receiver methods for command types: %s. " +
```
Comment (alexander-yevsyukov) [inline server/src/main/java/io/spine/server/model/ExternalCommandReceiverMethodError.java:60]: Please move `+` to next line. We do not check it automatically yet. But soon we'd do using Checkstyle.

File: server/src/test/java/io/spine/server/procman/ProcessManagerTest.java [hunk 3]
```diff
@@ -124,7 +124,7 @@
     private TestProcessManager processManager;
 
     @BeforeEach
-    void setUp() {
+    void initProcessManager() {
```
Comment (alexander-yevsyukov) [inline server/src/test/java/io/spine/server/procman/ProcessManagerTest.java:127]: A better name would be `initContextAndProcessManager()`. Just to play nicely with `closeContext()`.

File: client/src/main/java/io/spine/client/QueryFactory.java [hunk 4]
```diff
@@ -204,62 +201,64 @@ private static void checkSpecified(Class<? extends EntityState> entityClass) {
         return builder;
     }
 
+    @Internal
```
Comment (alexander-yevsyukov) [inline client/src/main/java/io/spine/client/QueryFactory.java:204]: Why do we want this annotation on the package-private code?

File: client/src/main/java/io/spine/client/QueryFactory.java [hunk 5]
```diff
@@ -204,62 +201,64 @@ private static void checkSpecified(Class<? extends EntityState> entityClass) {
...
-        Query.Builder builder = Query.newBuilder()
-                                     .setTarget(target);
-        return builder;
+        return composeQuery(target, 0, null, fieldMask);
     }
 
-    Query composeQuery(Target target,
-                       OrderBy orderBy,
-                       @Nullable FieldMask fieldMask) {
+    @Internal
```
Comment (alexander-yevsyukov) [inline client/src/main/java/io/spine/client/QueryFactory.java:210]: Why do we want this annotation on the package-private code?

File: client/src/main/java/io/spine/client/QueryFactory.java [hunk 6]
```diff
@@ -204,62 +201,64 @@ private static void checkSpecified(Class<? extends EntityState> entityClass) {
...
-        Query query = newQuery(builder);
-        return query;
+        return composeQuery(target, 0, orderBy, fieldMask);
     }
 
-    Query composeQuery(Target target,
-                       OrderBy orderBy,
-                       int limit,
-                       @Nullable FieldMask fieldMask) {
+    @Internal
```
Comment (alexander-yevsyukov) [inline client/src/main/java/io/spine/client/QueryFactory.java:217]: Why do we want this annotation on the package-private code?

File: testutil-server/src/main/java/io/spine/testing/server/blackbox/DiagnosticLogging.java [hunk 7]
```diff
@@ -0,0 +1,77 @@
...
+        boolean loggingEnabled = severeLogger.isEnabled();
+        if (loggingEnabled) {
+            severeLogger.log(msg);
+            severeLogger.log(toJson(event));
+        } else {
+            @SuppressWarnings("UseOfSystemOutOrSystemErr")
+            // Edge case for disabled/misconfigured logging .
+            PrintStream stderr = System.err;
+            stderr.println(msg);
+            stderr.println(toJson(event));
```
Comment (alexander-yevsyukov) [inline testutil-server/src/main/java/io/spine/testing/server/blackbox/DiagnosticLogging.java:74]: Please extract `toJson(Event)` into a variable. We use it in both `if` branches.

File: testutil-server/src/main/java/io/spine/testing/server/blackbox/FailedHandlerGuard.java [hunk 8]
```diff
@@ -0,0 +1,113 @@
...
+    }
+
+    /**
+     * {@inheritDoc}
+     *
+     * <p>The {@code BlackBoxBoundedContext} does not consume external events.
+     */
+    @Override
+    public ImmutableSet<EventClass> externalEventClasses() {
+        return ImmutableSet.of();
```
Comment (alexander-yevsyukov) [inline testutil-server/src/main/java/io/spine/testing/server/blackbox/FailedHandlerGuard.java:111]: How about introducing  `EventClass.emptySet()` so that it's easier to find places where return empty sets?

File: testutil-server/src/main/java/io/spine/testing/server/blackbox/HandlerFailureTolerance.java [hunk 9]
```diff
@@ -0,0 +1,38 @@
...
+
+    /**
+     * Identifies that exceptions must be only logged.
+     */
+    LOG,
+
+    /**
+     * Identifies that exceptions must be raised and tests must be failed.
+     */
+    RAISE
```
Comment (alexander-yevsyukov) [inline testutil-server/src/main/java/io/spine/testing/server/blackbox/HandlerFailureTolerance.java:37]: Consider naming it `RAISE_AND_FAIL`.

File: testutil-server/src/main/java/io/spine/testing/server/blackbox/HandlerFailureTolerance.java [hunk 10]
```diff
@@ -0,0 +1,38 @@
...
+ * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
+ */
+
+package io.spine.testing.server.blackbox;
+
+/**
+ * Configures the behavior of the {@link BlackBoxContext} on handling runtime exceptions
+ * thrown from the handler methods.
+ */
+public enum HandlerFailureTolerance {
```
Comment (alexander-yevsyukov) [inline testutil-server/src/main/java/io/spine/testing/server/blackbox/HandlerFailureTolerance.java:27]: Do we really need it to be public?

**Review by alexander-yevsyukov — CHANGES_REQUESTED** [review]
Please see my comments and questions.

**Comment by yuri-sergiichuk** [comment]
@alexander-yevsyukov PTAL again.

File: testutil-server/src/main/java/io/spine/testing/server/blackbox/HandlerFailureTolerance.java [hunk 11]
```diff
@@ -0,0 +1,38 @@
...
+ */
+enum HandlerFailureTolerance {
+
+    /**
+     * Identifies that exceptions must be only logged.
+     */
+    LOG,
+
+    /**
+     * Identifies that exceptions must be raised and tests must be failed.
```
Comment (dmdashenkov) [inline testutil-server/src/main/java/io/spine/testing/server/blackbox/HandlerFailureTolerance.java:35]: Maybe "thrown"?

Comment (yuri-sergiichuk) [reply testutil-server/src/main/java/io/spine/testing/server/blackbox/HandlerFailureTolerance.java:35]: I'd keep "raised" as we do not really intend to rethrow the exception.

**Comment by dmdashenkov** [comment]
@yuri-sergiichuk, LGTM as long as build passes.

**Review by dmdashenkov — APPROVED** [review]
@yuri-sergiichuk, LGTM, as long as @alexander-yevsyukov 's comments are resolved.

**Review by alexander-yevsyukov — APPROVED** [review]
LGTM
